# Generated by Django 2.1.1 on 2018-10-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makepost',
            name='info',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
